Add + and x as markers
bqplot/bqplot pull request #1506
Opened 2022-07-16 19:21 UTC by mwcraig

## References

There is not an open issue that I found.

## Code changes

See below 

## User-facing changes

This adds two more scatter marker shapes:

+ `plus`, which makes the shape `+`
+ `crosshair`, which makes the shape `×` 

## Backwards-incompatible changes

N/A

2022-07-16 19:21 UTC, mwcraig commented
@ibdafna @pllim

2022-07-16 22:18 UTC, pllim approved these changes
I like the new markers. Thanks!

Note to self: Open follow-up issue after this PR is merged to request "+" to be changed to thin "+" sign and "P" (uppercase P) to be the current "thick +" sign that is mapped to "+" symbol.

2022-07-16 22:39 UTC, ibdafna commented
Thanks for the PR, Matt! For what it's worth, the pyplot interface was not
designed with for compatibility with matplotlib. It's an issue we want to
resolve for 1.x. Chakri can probably discuss it in more details as it's his
implementation

On Sat, Jul 16, 2022, 15:18 P. L. Lim ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> I like the new markers. Thanks!
>
> Note to self: Open follow-up issue after this PR is merged to request "+"
> to be changed to thin "+" sign and "P" (uppercase P) to be the current
> "thick +" sign that is mapped to "+" symbol.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bqplot/bqplot/pull/1506#pullrequestreview-1041031731>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFZICWMBJUCHCXD5EBH4HUTVUMYMZANCNFSM53YQXAUA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-17 18:38 UTC, ibdafna commented
Will dig into the visual regression test during the week. Looks like node is failing building node-pre-gyp for some reason.

2022-07-21 22:52 UTC, ibdafna requested changes
@mwcraig Thanks again for this PR! 🤗

Would it be possible to make the addition consistent by adding the new marker annotations to the following places?

- https://github.com/bqplot/bqplot/pull/1506/files#diff-fd3647496cb92f713ffed86551cf5eb1ab870896603af2be0f35e549bed8ebd4R409
- https://github.com/bqplot/bqplot/pull/1506/files#diff-fd3647496cb92f713ffed86551cf5eb1ab870896603af2be0f35e549bed8ebd4R330

Also, an updated example in the Lines.ipynb (where we list the different available markers) notebook would be awesome! 

![image](https://user-images.githubusercontent.com/24281433/180328160-fbf1ce2c-b500-44e2-8d7d-288510cbe410.png)

And finally, once the notebook above is updated, we can add some visual regression testing via this PR. Thanks again! 💚

2022-09-23 14:34 UTC, mwcraig commented
@ibdafna -- I've addressed the review comments.

2022-09-29 13:24 UTC, martinRenou approved these changes
Thanks a lot Matt!

2022-09-29 13:24 UTC, merged

2022-09-29 14:15 UTC, martinRenou commented
meeseeksdev please backport to 0.12.x